### Example LDAP directory configuration ###

sampleDirectoryServer.enable = true
sampleDirectoryServer.port = 11389
sampleDirectoryServer.operations = BIND, COMPARE, SEARCH, EXTENDED
sampleDirectoryServer.schema = /WEB-INF/sampleDirectorySchema.ldif
sampleDirectoryServer.baseDN = dc=wonderland,dc=net
sampleDirectoryServer.content = /WEB-INF/sampleDirectoryContent.ldif

