### ### OAuth 2.0 / OpenID Connect authorisation store configuration ### ###

# The default configuration of the store for authorisations and related
# information. Can be overridden with Java system properties.
#
# https://connect2id.com/products/server/docs/config/authz-store


### Web API ###

# The access token for the authorisation store web API, represented by its
# SHA-256 hash (in hexadecimal format). The hash is a measure to prevent
# accidental leakage of the token through configuration files, logs, etc. The
# token is of type Bearer, non-expiring and must contain at least 32 random
# alphanumeric characters to make brute force guessing impractical. If not
# specified the web API is disabled.
#
# Additional access tokens, for token roll-over or other needs, can be
# configured by appending a dot (.) with a unique label to the property name,
# e.g. as authzStore.apiAccessTokenSHA256.1=abc...
#
# Evaluation note: Use token value ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6
authzStore.apiAccessTokenSHA256=cca68b8b82bcf0b96cb826199429e50cd95a042f8e8891d1ac56ab135d096633


### Authorisation code ###

# The authorisation code lifetime in seconds. Should be long enough to permit a
# client to make a token request to exchange the code for an ID / access token.
# Must not be shorter than 60 seconds (1 minute) or longer than 600 seconds (10
# minutes). The default value is 300 seconds (5 minutes).
authzStore.code.lifetime=300


### Access token ###

# The default access token lifetime in seconds. Can be overridden by individual
# authorisations. Must be a positive integer. The default value is 600 seconds
# (10 minutes).
authzStore.accessToken.defaultLifetime=600

# The JSON Web Signature (JWS) algorithm for signing the self-contained (JWT)
# access tokens. Must be a valid and supported RSA-SSA, ECDSA or EdDSA JWS
# algorithm. The default value is RS256.
#
# Supported JWS algorithms:
#
#     * RS256 (default, recommended)
#     * RS384
#     * RS512
#     * PS256
#     * PS384
#     * PS512
#     * ES256
#     * ES256K
#     * ES384
#     * ES512
#     * EdDSA (with Ed25519 key, recommended for high-performance and compact
#       signatures)
#
authzStore.accessToken.jwsAlg=RS256

# The JSON Web Encryption (JWE) algorithm for the self-contained (JWT) access
# tokens which are encrypted after signing. Only direct encryption (dir) with a
# shared key is supported. The default value is dir.
#
# Supported JWE algorithms:
#
#     * dir (default)
#
authzStore.accessToken.jweAlg=dir

# The JSON Web Encryption (JWE) method for the self-contained (JWT) access
# tokens which are encrypted after signing. Must be a valid and supported JWE
# method. The default value is A128GCM.
#
# Supported JWE methods:
#
#     * A128GCM (default, recommended)
#     * A192GCM
#     * A256GCM
#     * A128CBC_HS256
#     * A192CBC_HS384
#     * A256CBC_HS512
#     * XC20P
#
authzStore.accessToken.jweEnc=A128GCM

# Enables / disables inclusion of the X.509 certificate chain ("x5c") header
# parameter in issued self-contained (JWT) access tokens when the signing JWK
# is provisioned with a certificate. The default value is true (enabled).
authzStore.accessToken.includeX5C=true

# If true an access token can be inspected without presenting the master Bearer
# access token to the authorisation store web API. The default value is false
# (disabled).
authzStore.accessToken.allowDirectInspection=false

# When true disables the automatic encryption of self-contained (JWT-encoded)
# access tokens with public (non-pairwise) subject identifiers, in cases when
# the access tokens are issued to clients registered for pairwise subjects in
# ID tokens and UserInfo responses. The default value is false.
authzStore.accessToken.disableSubjectSecurity=false

# The JWT profile of access tokens minted by the default self-contained access
# token encoder / decoder. If a custom JWT codec is plugged in (see the
# SelfContainedAccessTokenClaimsCodec SPI JavaDoc) this setting has no effect.
# The default value is c2id-1.1.
#
# Supported profiles:
#
#     * c2id-1.1 -- Connect2id server specific profile, available since v7.17,
#       with the JWT "typ" (type) header set to "at+jwt". This is the default
#       profile.
#     * c2id-1.0 -- Connect2id server specific profile, available since v1.0,
#       outputs identical JWT claims as c2id-1.1 but doesn't set the JWT "typ"
#       (type) header.
#     * oauth-1.0 -- Standard profile developed in the OAuth working group, see
#       RFC 9068.
#
authzStore.accessToken.codec.jwt.profile=c2id-1.1

# Names of members in the client registration's "data" JSON object to copy as
# top-level JWT claims in access tokens minted by the default self-contained
# access token encoder. An "*" (asterisk) selects all members. The member names
# can alternatively be specified as comma and / or space separated list. If a
# custom JWT codec is plugged in (see the SelfContainedAccessTokenClaimsCodec
# SPI JavaDoc) this setting has no effect. The default value is none.
authzStore.accessToken.codec.jwt.copyClientData=

# Names of members in the authorisation "dat" (data) JSON object to move to
# top-level JWT claims in access tokens minted by the default self-contained
# access token encoder. An "*" (asterisk) selects all members. The member names
# can alternatively be specified as comma and / or space separated list. If a
# custom JWT codec is plugged in (see the SelfContainedAccessTokenClaimsCodec
# SPI JavaDoc) this setting has no effect. The default value is none.
authzStore.accessToken.codec.jwt.moveAuthzData=


### Refresh token ###

# The default refresh token lifetime in seconds. Can be overridden by
# individual authorisations. If zero or omitted defaults to permanent (no
# expiration). Must be zero or a positive integer. The default value is zero
# (no expiration).
authzStore.refreshToken.defaultLifetime=0

# The default refresh token rotation setting. Can be overridden by individual
# authorisations. The default value is false (no rotation).
authzStore.refreshToken.defaultRotate=false

# If true causes the refresh token to be updated (rotated) on each
# authorisation update and on each refresh token use. The default value is
# false (no update). Deprecated in v14.0.
authzStore.refreshToken.alwaysUpdate=

# Grace period in seconds during which a client may repeat a request with the
# same rotated refresh token without triggering the customary token revocation.
# Intended to enable token request retrial on slow / poor networks where the
# HTTP response times out after issue of the new token. Currently supported
# only for refresh tokens linked to short-lived (transient) authorisations. The
# default value is 5 seconds.
authzStore.refreshToken.rotatedReuseGracePeriod=5


### Revocation ###

# Adjusts the checking of revocation timestamps by adding a negative or
# positive time bias, in seconds. The default value is 0 seconds (no bias).
#
# A token is deemed active (non-revoked) if there are no recorded revocations
# for the token subject and / or client ID after the token issued-at time
# ("iat"). The resolution of revocations and token issued-at times is in
# seconds.
#
# With no (zero) bias tokens issued at the same second when a revocation is
# recorded are considered active (non-revoked). This enables a subject and / or
# client ID to have its tokens revoked and then be immediately issued again
# with active tokens, within the same second.
#
# A positive bias of 1 ensures tokens issued within the same second of a
# revocation are considered revoked, preventing any ambiguity in the time
# sequence of revocation and token issue events. A bias greater than 1 should
# generally not be used.
#
# A negative bias can mitigate false revocation positives in a Connect2id
# server cluster where the clocks of the individual server instances are out of
# sync.
authzStore.revocation.checkBias=0


### Authorisation store options ###

# With an enabled highly-available mode the authorisation store will continue
# providing basic service even if the backend database is down or disconnected.
# The required data will be served from the caches if possible and database
# connection exceptions will not cause requests to fail (they will be logged at
# ERROR level however). The default value is true (enabled).
authzStore.options.highlyAvailableMode=true

# List of the optional authorisation attributes that are to be automatically
# discarded from new authorisation objects, in order to conserve cache memory
# and back-end storage. The default value is none.
authzStore.options.discardedAttributes=

# If true the Connect2id server will issue refresh tokens in the legacy format
# supported up to v7.x. Intended to facilitate seamless rolling upgrades to
# v8.x and later. The default value is false (no issue of legacy refresh
# tokens).
authzStore.options.issueLegacyRefreshTokens=false