### ### OpenID claim names compression dictionary ### ###

# The default definition of a dictionary for compressing lists of OpenID claim
# names in issued self-contained (JWT) access tokens. Can be overridden with
# Java system properties.
#
# https://connect2id.com/products/server/docs/config/access-token-compression

0=sub
1=email
2=email_verified
3=phone_number
4=phone_number_verified
5=name
6=family_name
7=given_name
8=middle_name
9=nickname
10=preferred_username
11=profile
12=picture
13=website
14=gender
15=birthdate
16=zoneinfo
17=locale
18=updated_at
19=address

# You can add other custom claim names for compression below this line