### ### OAuth 2.0 client credentials grant handler configuration ### ###

# The default configuration of the web-based handler for client credentials
# grants. Can be overridden with Java system properties.
#
# https://connect2id.com/products/server/docs/integration/client-credentials-grant-handler#web-implementation

# Enables / disables the grant handler. Disabled (false) by default.
op.grantHandler.clientCredentials.webAPI.enable=false

# The endpoint URL of the web API.
op.grantHandler.clientCredentials.webAPI.url=

# Access token of type Bearer for the web API.
op.grantHandler.clientCredentials.webAPI.apiAccessToken=

# Names of custom token request parameters to include as top-level members in
# the handler request JSON object. The default value is none.
op.grantHandler.clientCredentials.customParams=

# Names of client metadata fields to include in the "client" JSON object which
# is part of handler request. If not specified the following client metadata
# fields are included by default: "scope", "application_type",
# "sector_identifier_uri", "subject_type", "default_max_age",
# "require_auth_time", "default_acr_values", "data".
op.grantHandler.clientCredentials.clientMetadata=

# The HTTP connect timeout, in milliseconds. The default value is zero, implies
# none or determined by the underlying HTTP client.
op.grantHandler.clientCredentials.webAPI.connectTimeout=250

# The HTTP response read timeout, in milliseconds. The default value is zero,
# implies none or determined by the underlying HTTP client.
op.grantHandler.clientCredentials.webAPI.readTimeout=500