### ### Cross-Origin Resource Sharing (CORS) Filter configuration ### ###

# The default configuration for CORS handling. Can be overridden with Java
# system properties.
#
# https://connect2id.com/products/server/docs/config/cors

# Set to "false" to disable the CORS Filter, causing it to pass all HTTP
# requests. The CORS Filter can be disabled if the Connect2id server is
# provisioned with a reverse proxy handling CORS. Otherwise the CORS Filter
# should be left enabled, to process cross-domain requests according to its
# configuration. The default value if omitted is "true" (enabled).
cors.enable=true

# Set to "true" to allow generic HTTP requests, else only valid and accepted
# CORS requests will be allowed (strict CORS filtering).
#
# Recommended value: "true"
cors.allowGenericHttpRequests=true

# Lists the allowed CORS origins. They must be specified as 
# whitespace-separated URLs. Requests from origins not included here will be
# refused with an HTTP 403 "Forbidden" response. If set to "*" all origins will
# be allowed.
cors.allowOrigin=*

# Set to "true" to allow requests from any origin which is a subdomain origin
# of cors.allowOrigin.
#
# Example:
#
# Explicitly allowed origin: http://example.com
#
# Matches the original origin as well as any subdomain, e.g. 
# http://foo.example.com, http://bar.example.com, etc.
cors.allowSubdomains=false

# Lists the supported HTTP methods. Requests for methods not included here will
# be refused by the CORS filter with an HTTP 405 "Method not allowed" response.
cors.supportedMethods=GET,POST,PUT,DELETE

# Lists the supported non-simple (according to the CORS standard) header names.
cors.supportedHeaders=*

# Lists the non-simple headers (according to the CORS standard) that the web
# client (browser) should expose.
cors.exposedHeaders=Location

# Indicates whether user credentials, such as cookies, HTTP authentication or
# client-side certificates, are supported.
cors.supportsCredentials=true

# Indicates how long the results of a CORS preflight request can be cached by
# the web client, in seconds. If -1 unspecified.
#
# Recommended value: 1 day (86400 seconds).
cors.maxAge=86400
