### ### Custom scopes for OpenID claims ### ###

# The default definition of custom scope values for requesting a set of one or
# more OpenID claims. Can be overridden with Java system properties.
#
# https://connect2id.com/products/server/docs/config/claims-mapping
#
# Example:
#
# scope_A=claim_A1,claim_A2,claim_A3,...
# scope_B=claim_B1,claim_B2,...
# scope_C=claim_C1,...
