### ### OpenID Connect device SSO handler configuration ### ###

# The default configuration of the local handler for OpenID Connect
# back-channel device SSO requests. Can be overridden with Java system
# properties.
#
# https://connect2id.com/products/server/docs/integration/device-sso-handler#default

# Enables / disables the handler. Disabled (false) by default.
op.deviceSSOHandler.enable=true

# Scope values that require end-user interaction (re-authentication or explicit
# consent) at the authorisation endpoint, as space separated list. Back-channel
# device SSO requests that include any of these scope values will trigger an
# "interaction_required" error at the token endpoint. None by default.
op.deviceSSOHandler.scopeRequiringInteraction=


### Access token ###

# The access token lifetime, in seconds. If zero, blank or omitted the default
# access token lifetime configured by "authzStore.accessToken.defaultLifetime"
# applies.
op.deviceSSOHandler.accessToken.lifetime=

# The access token encoding. The default value is SELF_CONTAINED.
#
# Supported encodings:
#
#     * IDENTIFIER -- The access token is a secure identifier. The associated
#       authorisation is looked up by a call to the Connect2id server token
#       introspection endpoint.
#     * SELF_CONTAINED -- Self-contained access token. The associated
#       authorisation is encoded in the access token itself, as a signed and
#       optionally encrypted JSON Web Token (JWT). Can also be looked up by a
#       call to the Connect2id server token introspection endpoint.
#
op.deviceSSOHandler.accessToken.encoding=SELF_CONTAINED

# If true enables additional encryption of self-contained (JWT-encoded) access
# tokens. Disabled (false) by default.
op.deviceSSOHandler.accessToken.encrypt=false

# Optional audience for the access tokens, as comma and / or space separated
# list of values.
op.deviceSSOHandler.accessToken.audienceList=

# Names of client metadata fields to include in the optional access token
# "data" field, empty set if none. To specify a member within a field that is a
# JSON object member use dot (.) notation.
op.deviceSSOHandler.accessToken.includeClientMetadataFields=


### Refresh token ###

# Enables / disables refresh token issue. Enabled (true) by default.
op.deviceSSOHandler.refreshToken.issue=true

# The refresh token lifetime, in seconds. Zero for no expiration. If -1, blank
# or omitted the default refresh token lifetime configured by
# "authzStore.refreshToken.defaultLifetime" applies.
op.deviceSSOHandler.refreshToken.lifetime=

# The refresh token maximum idle time, in seconds. Zero for no idle time
# expiration. The default value is 0.
op.deviceSSOHandler.refreshToken.maxIdleTime=0

# If true causes the refresh token to be updated (rotated) on each refresh
# token use. If blank or omitted the default rotation setting configured by
# "op.deviceSSOHandler.refreshToken.rotate" applies.
op.deviceSSOHandler.refreshToken.rotate=

# The transport to use for authorised claims. The default value is USERINFO:
#
# Supported values:
#
#     * USERINFO -- To release the claims at the UserInfo endpoint of the
#       Connect2id server by presenting the issued access token.
#     * ID_TOKEN -- To release the claims in the ID token. If an ID token is
#       not issued for a particular request the claims will be diverted for
#       release at the UserInfo endpoint.
#
op.deviceSSOHandler.claimsTransport=USERINFO