### ### HTTP claims source configuration ### ###

# The default configuration for an HTTP endpoint source of OpenID claims for
# the UserInfo endpoint and ID tokens. Can be overridden with Java system
# properties.
#
# https://connect2id.com/products/server/docs/config/claims-sources#http

# Enables / disables the claims source. Disabled by default.
op.httpClaimsSource.enable=false

# The names of the supported (standard and custom) OpenID Connect claims, as a
# comma and / or space separated list. Support for a pattern of claims can be
# indicated with the "*" wildcard character, for example as
# "https://idp.example.com/*" for a set of claims having a common URI prefix in
# their name. A single claim set to "*" indicates support for all claims
# supported by the OpenID provider without explicitly listing them.
op.httpClaimsSource.supportedClaims=email,email_verified,name,given_name,family_name

# The URL of the HTTP endpoint for sourcing the OpenID Connect claims. Should
# be HTTPS.
op.httpClaimsSource.url=https://example.com/claims-source

# The timeout in milliseconds for establishing HTTP connections. If zero the
# underlying HTTP client library will determine the timeout.
op.httpClaimsSource.connectTimeout=1000

# The timeout in milliseconds for obtaining HTTP responses after connection. If
# zero the underlying HTTP client library will determine the timeout.
op.httpClaimsSource.readTimeout=1000

# Determines whether to accept self-signed X.509 / TLS certificates presented
# by the HTTP server. Self-signed certificates are not trusted by default.
op.httpClaimsSource.trustSelfSignedCerts=false

# Access token of type bearer (non-expiring) for accessing the HTTP endpoint.
# Should contain at least 32 random alphanumeric characters to make brute force
# guessing impractical.
op.httpClaimsSource.apiAccessToken=ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6

# Enables / disables inclusion in the request of the subject (end-user) session
# ID where the claims sourcing was authorised. Disabled by default.
op.httpClaimsSource.includeSubjectSessionID=false

# Enables / disables inclusion in the request of the subject (end-user) session
# where the claims sourcing was authorised. Disabled by default.
op.httpClaimsSource.includeSubjectSession=false