### ### LDAP claims source configuration ### ###

# The default configuration for an LDAP source of OpenID claims for the
# UserInfo endpoint and ID tokens. Can be overridden with Java system
# properties.
#
# https://connect2id.com/products/server/docs/config/claims-sources#ldap


### Enable / disable ###

# Enables / disables the claims source. Disabled by default.
op.ldapClaimsSource.enable=true

# Optional property for passing the LDAP attribute map by value or from an
# alternative resource location:
#
#     * Set the property value to the JSON object representation of the LDAP
#       attribute map. The JSON string can be additionally BASE-64 encoded to
#       ease passing the value as a Java system property (the claims source
#       will automatically detect that and decode it back to JSON string).
#
#     * Set the property value to a file location relative to the web
#       application root.
#
# If the property isn't set the LDAP claims source will load the attribute map
# from the default "/WEB-INF/ldapClaimsMap.json" location.
op.ldapClaimsSource.attributeMap=/WEB-INF/ldapClaimsMap.json


### LDAP server details ###

# The LDAP URL of the directory server for sourcing the claims. The schema must
# be ldap or ldaps, it must specify a valid host name or IP address as well as
# the port number if a non-default is used.
#
# If the directory is replicated across several LDAP servers for the purpose of
# fail-over or load-balancing, the value is a space-separated list of the
# corresponding LDAP URLs. Server selection is handled according to
# op.ldapClaimsSource.ldapServer.selectionAlgorithm.
op.ldapClaimsSource.server.url=ldap://127.0.0.1:11389

# The preferred server selection algorithm in case op.ldapClaimsSource.server.
# url is an LDAP server set:
#
#     * FAILOVER -- Establish connections to the LDAP servers in the order they
#       are provided. If the first server is unavailable, then it will attempt
#       to connect to the second, then to the third and so on.
#     * ROUND-ROBIN -- Use a round-robin algorithm to select the LDAP server to
#       which the connection should be established. Any number of servers may
#       be included in the set and each request will attempt to retrieve a
#       connection to the next server in the list, circling back to the
#       beginning of the list as necessary. If a server is unavailable when an
#       attempt is made to establish a connection to it, then the connection
#       will be established to the next available server in the list.
#
op.ldapClaimsSource.server.selectionAlgorithm=

# The timeout in milliseconds for LDAP connect requests. If zero the underlying
# LDAP client library will handle this value.
op.ldapClaimsSource.server.connectTimeout=250

# The LDAP connection security:
#
#     * NONE -- establish a plain insecure connection.
#     * SSL -- establish a secure connection over SSL.
#     * StartTLS -- establish a secure connection using the StartTLS protocol
#       (recommended method).
#
op.ldapClaimsSource.server.security=NONE

# Determines whether to accept self-signed certificates presented by the LDAP
# server (for secure SSL or StartTLS connections). Self-signed certificates are
# not trusted by default.
op.ldapClaimsSource.server.trustSelfSignedCerts=false

# The maximum LDAP connection pool size. The default value is five connections.
op.ldapClaimsSource.server.connectionPoolSize=5

# The initial LDAP connection pool size. The acceptable range is between
# zero and the maximum LDAP connection pool size (inclusive). Set it to zero to
# enable startup of the Connect2id server without the backend LDAP directory
# being available.
op.ldapClaimsSource.server.connectionPoolInitialSize=0

# The maximum length of time in milliseconds to wait for a connection to become
# available when trying to obtain an LDAP connection from the pool. A value of
# zero should be used to indicate that the pool should not block at all if no
# connections are available and that it should either create a new connection
# or throw an exception.
op.ldapClaimsSource.server.connectionPoolMaxWaitTime=250

# The maximum time in milliseconds that an LDAP connection in the pool may be
# established before it should be closed and replaced with another connection.
# A value of zero indicates that no maximum age should be enforced. Defaults to
# no maximum age (zero).
op.ldapClaimsSource.server.connectionMaxAge=0


### LDAP user details ###

# The distinguished name (DN) of the LDAP directory user to perform the claims
# retrieval operations. Must have search and read access to the directory
# branch containing the subject entries. An empty value implies an anonymous
# user.
op.ldapClaimsSource.directory.user.dn=uid=alice,ou=people,dc=wonderland,dc=net

# The directory user password. An empty value implies an anonymous user.
op.ldapClaimsSource.directory.user.password=secret


### LDAP search configuration ###

# The base distinguished name (DN) of the LDAP directory branch where the
# subject entries are stored.
op.ldapClaimsSource.directory.baseDN=ou=people,dc=wonderland,dc=net

# The LDAP search scope for the subject entries with respect to the base DN
# specified in op.ldapClaimsSource.directory.baseDN:
#
#     ONE -- indicates that only entries that are immediate subordinates of
#     the base entry (but not the base entry itself) should be considered.
#
#     SUB -- Indicates that the base entry itself and any subordinate entries
#     (to any depth) should be considered.
#
#     SUBORDINATE_SUBTREE -- Indicates that any subordinate entries (to any
#     depth) below the base entry should be considered, but the base entry
#     itself should not be considered, as described in
#     draft-sermersheim-ldap-subordinate-scope.
#
op.ldapClaimsSource.directory.scope=ONE

# The LDAP search filter to retrieve the subject entries. The "%u" placeholder
# will be substituted with the subject identifier (sub).
op.ldapClaimsSource.directory.filter=(uid=%u)


### Custom LDAP server trust and key store ###

# Set to true to use your custom trust store file for determining the
# acceptable security certificates presented by the remote LDAP server.
#
# Set to false to use the default trust store of the web server / host system
# (if one has been provided and correctly configured).
#
# If you set this to true you must also specify a trust store file, type and
# password (see the corresponding parameters below).
op.ldapClaimsSource.customTrustStore.enable=false

# The location of the custom trust store file.
op.ldapClaimsSource.customTrustStore.file=

# The password required to unlock the trust store file. Leave it empty if none
# is required.
op.ldapClaimsSource.customTrustStore.password=

# The type of the trust store file, typically JKS or PKCS12. Leave it empty to
# assume the system default type.
op.ldapClaimsSource.customTrustStore.type=

# Set to true to use your custom key store file for client security
# certificates to be presented to the remote LDAP server requiring such
# authentication.
#
# Set to false to use the default key store of the web server / host system (if
# one has been provided and correctly configured).
#
# If you set this to true you must also specify a key store file, type and
# password (see the corresponding parameters below).
op.ldapClaimsSource.customKeyStore.enable=false

# The location of the custom key store file.
op.ldapClaimsSource.customKeyStore.file=

# The password required to unlock the key store file. Leave it empty if none is
# required.
op.ldapClaimsSource.customKeyStore.password=

# The type of the trust store file, typically JKS or PKCS12. Leave it empty to
# assume the system default type.
op.ldapClaimsSource.customKeyStore.type=