### ### Connect2id Server OpenID Federation 1.0 Trust Anchor Configuration ### ###

# This is to store Trust Anchors in a separate properties file to avoid hard-coding of Trust Anchor identifiers.

# The URL identifying the Trust Anchor of this Federation.

ota.trustAnchor.1=
ota.trustAnchor.2=
ota.trustAnchor.3=


