### ### OAuth 2.0 token exchange grant handler configuration ### ###

# The default configuration of the web-based handler for token exchange grants.
# Can be overridden with Java system properties.
#
# https://connect2id.com/products/server/docs/integration/token-exchange-grant-handler#web-implementation

# Enables / disables the grant handler. Disabled (false) by default.
op.grantHandler.tokenExchange.webAPI.enable=false

# The endpoint URL of the web API.
op.grantHandler.tokenExchange.webAPI.url=

# Access token of type Bearer for the web API.
op.grantHandler.tokenExchange.webAPI.apiAccessToken=

# Names of custom token request parameters to include as top-level members in
# the handler request JSON object. The default value is none.
op.grantHandler.tokenExchange.customParams=

# Names of client metadata fields to include in the "client" JSON object which
# is part of handler request. If not specified the following client metadata
# fields are included by default: "scope", "application_type",
# "sector_identifier_uri", "subject_type", "default_max_age",
# "require_auth_time", "default_acr_values", "data".
op.grantHandler.tokenExchange.clientMetadata=

# The accepted subject token types, as comma and / or space separated list.
# The default value is "*" (asterisk) indicating all types.
op.grantHandler.tokenExchange.webAPI.subjectToken.types=*

# Enables / disables introspection of subject tokens of type access token as
# locally issued access tokens. If enabled the introspection takes place before
# invoking the web API and on success will include the token introspection
# response from the Connect2id server. The default value is false (no
# introspection of local access tokens).
op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.local.enable=false

# One or more optional remote introspections to perform on subject tokens of
# type access token. If specified the introspection takes place sequentially
# before invoking the web API and on success at any one of the configured
# introspection endpoints will include its token introspection response.
#
# The configured introspection endpoints must be compliant with RFC 7662.
#
# If a client authentication method is specified, it must be
# "client_secret_basic" and include a client ID and client secret for the
# caller. Other authentication methods may be supported in future.
#
# If no client authentication method is specified the default value is "none"
# (no client authentication).
#
# An HTTP connect and response read timeout, in milliseconds, may be specified.
# The default timeouts are zero, implying none or determined by the underlying
# HTTP client.
#
# Example with two remote introspection endpoints:
#
# op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.remote.1.endpoint=https://op.example.com/token/introspect
# op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.remote.1.authMethod=client_secret_basic
# op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.remote.1.clientID=123
# op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.remote.1.clientSecret=airo8Muawi5tuuLo
# op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.remote.1.connectTimeout=1000
# op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.remote.1.readTimeout=2000
# op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.remote.2.endpoint=https://oauth.example.org/token/introspect
# op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.remote.2.authMethod=none
# op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.remote.2.connectTimeout=0
# op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.remote.2.readTimeout=0

# Enables / disables the "must pass" requirement for introspected subject
# tokens of type access token. The default value is true, meaning access tokens
# must successfully pass local or remote introspection before the Connect2id
# server invokes the web API, else an "invalid_request" error will be returned
# to the client. If false the web API will also be invoked for access tokens
# that failed the configured introspection, for example to let the web-based
# handler perform its own introspection.
op.grantHandler.tokenExchange.webAPI.subjectToken.accessTokenIntrospection.mustPass=

# One or more optional JWK set URLs to perform JWT signature verification of
# subject types of type explicit JWT, access token or ID token. If specified
# the JWK sets URLs will be used sequentially to retrieve key candidates for
# the signature verification. After retrieval the JWK sets are cached locally.
#
# An HTTP connect and response read timeout, in milliseconds, may be specified.
# The default timeouts are zero, implying none or determined by the underlying
# HTTP client.
#
# Example with two JWK set URLs:
#
# op.grantHandler.tokenExchange.webAPI.subjectToken.jwtVerification.1.jwkSetURI=https://op.example.com/jwks.json
# op.grantHandler.tokenExchange.webAPI.subjectToken.jwtVerification.1.connectTimeout=1000
# op.grantHandler.tokenExchange.webAPI.subjectToken.jwtVerification.1.readTimeout=1000
# op.grantHandler.tokenExchange.webAPI.subjectToken.jwtVerification.2.jwkSetURI=https://sts.example.org/jwks.json

# Enables / disables the "must pass" requirement for JWT verification of
# subject tokens of type explicit JWT, access token or ID token. The default
# value is true, meaning JWTs must successfully pass the signature verification
# and optional claims validation before the Connect2id server invokes the web
# API, else an "invalid_request" error will be returned to the client. If false
# the web API will also be invoked for JWTs that failed the verification, for
# example to let the web-based handler perform its own.
op.grantHandler.tokenExchange.webAPI.subjectToken.jwtVerification.mustPass=

# The accepted actor token types, as comma and / or space separated list. An
# "*" (asterisk) indicates all types. The default value is none (empty).
op.grantHandler.tokenExchange.webAPI.actorToken.types=

# The accepted requested token types, as comma and / or space separated list.
# The default value is "*" (asterisk) indicating all types.
op.grantHandler.tokenExchange.webAPI.requestedToken.types=*

# The HTTP connect timeout, in milliseconds. The default value is zero, implies
# none or determined by the underlying HTTP client.
op.grantHandler.tokenExchange.webAPI.connectTimeout=250

# The HTTP response read timeout, in milliseconds. The default value is zero,
# implies none or determined by the underlying HTTP client.
op.grantHandler.tokenExchange.webAPI.readTimeout=500
