# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    devtools:
        restart:
            enabled: true
        livereload:
            # we use gulp + BrowserSync for livereload
            enabled: false
    jackson:
        serialization.indent_output: true
    data:
    messages:
        cache-seconds: 1

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias c2idlogin -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        keyStoreType: PKCS12
#        keyAlias: c2idlogin
# ===================================================================
server:
    port: 8000

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# ===================================================================

c2id:
    endpoint: http://localhost:8080/c2id
    cookieName: sid
    authz:
        # Connect2id authorisation session API vars
        # See https://connect2id.com/products/server/docs/integration/authz-session
        resourcePath: /authz-sessions/rest/v3
        accessToken: ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6
        longLived: true
    session:
        # Connect2id user session store API vars
        # See https://connect2id.com/products/server/docs/integration/session-store
        resourcePath: /session-store/rest/v2
        accessToken: ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6
    ldapAuth:
        # LdapAuth API var (username + password verification against LDAP directory)
        # See https://connect2id.com/products/ldapauth/web-api
        endpoint: http://localhost:8080/ldapauth/
        apiKey: ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6
    logout:
        # Logout (End-Session) vars
        # See https://connect2id.com/products/server/docs/integration/logout-session
        resourcePath: /logout-sessions/rest/v1
        accessToken: ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6
        #redirectUri: optional
