IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='jwks' and xtype='U') CREATE TABLE jwks (ctx VARCHAR(10) NOT NULL, ts DATETIME NOT NULL, jwks VARCHAR(MAX) NOT NULL, CONSTRAINT pk_jwks PRIMARY KEY (ctx))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='jwks_history' and xtype='U') CREATE TABLE jwks_history (ts DATETIME NOT NULL, ctx VARCHAR(10) NOT NULL, jwks VARCHAR(MAX) NOT NULL, CONSTRAINT pk_jwks_history PRIMARY KEY (ts, ctx))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='subject_sessions' and xtype='U') CREATE TABLE subject_sessions (id VARCHAR(80) NOT NULL, sub VARCHAR(250) NOT NULL, auth_ts DATETIME NOT NULL, acr VARCHAR(100), amr VARCHAR(200), creation_ts DATETIME NOT NULL, access_ts DATETIME NOT NULL, ctx VARCHAR(10), jkt BINARY(32), fpt BINARY(32), max_life INT DEFAULT -1, auth_life INT DEFAULT -1, max_idle INT DEFAULT -1, claims NVARCHAR(4000), rps VARCHAR(2000), data NVARCHAR(4000), CONSTRAINT pk_subject_sessions PRIMARY KEY (id))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='subject_index' and xtype='U') CREATE TABLE subject_index (sub VARCHAR(500) NOT NULL, n INT NOT NULL, id VARCHAR(80) NOT NULL, CONSTRAINT pk_subject_index PRIMARY KEY (sub, n))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='pending_codes' and xtype='U') CREATE TABLE pending_codes (code VARCHAR(80) NOT NULL, authz NVARCHAR(MAX) NOT NULL, acl BIGINT DEFAULT -1, CONSTRAINT pk_pending_codes PRIMARY KEY (code))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='id_access_tokens' and xtype='U') CREATE TABLE id_access_tokens (id VARCHAR(500) NOT NULL, sub VARCHAR(250) NOT NULL, act VARCHAR(250), cid VARCHAR(100) NOT NULL, scp VARCHAR(2000), atl BIGINT DEFAULT -1, ats VARCHAR(10) NOT NULL DEFAULT 'PUBLIC', iss VARCHAR(250), iat DATETIME NULL, aud VARCHAR(250), clm NVARCHAR(2000), cll VARCHAR(100), cld NVARCHAR(2000), uip NVARCHAR(2000), sik VARCHAR(80), dat NVARCHAR(2000), oth NVARCHAR(2000), cnf VARCHAR(150), CONSTRAINT pk_id_access_tokens PRIMARY KEY (id))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='long_lived_authorizations' and xtype='U') CREATE TABLE long_lived_authorizations (sub VARCHAR(250) NOT NULL, act VARCHAR(250) NOT NULL, cid VARCHAR(100) NOT NULL, scp VARCHAR(2000), scs VARCHAR(2000), irt BIT NOT NULL, rtl BIGINT DEFAULT 0, rtm BIGINT DEFAULT 0, rtr BIT, idr BIT, rts VARCHAR(100), rti DATETIME NULL, atl BIGINT DEFAULT 0, ate VARCHAR(20) NOT NULL, atc BIT NOT NULL, ats VARCHAR(10) NOT NULL DEFAULT 'PUBLIC', iss VARCHAR(250), iat DATETIME NULL, uat DATETIME NULL, aud VARCHAR(500), clm NVARCHAR(2000), cll VARCHAR(100), cls NVARCHAR(2000), cld NVARCHAR(2000), uip NVARCHAR(2000), dat NVARCHAR(2000), CONSTRAINT pk_long_lived_authorizations PRIMARY KEY (sub, act, cid))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='revocation_journal' and xtype='U') CREATE TABLE revocation_journal (sub VARCHAR(250) NOT NULL, act VARCHAR(250) NOT NULL, cid VARCHAR(100) NOT NULL, ts DATETIME NOT NULL, CONSTRAINT pk_revocation_journal PRIMARY KEY (sub, act, cid))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='expended_tokens' and xtype='U') CREATE TABLE expended_tokens (t_key VARCHAR(100) NOT NULL,type CHAR(2) NOT NULL,ts DATETIME NOT NULL,tsp DATETIME,dat VARCHAR(2000),etl BIGINT, CONSTRAINT pk_expended_tokens PRIMARY KEY (t_key))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='auth_sessions' and xtype='U') CREATE TABLE auth_sessions (sid VARCHAR(100) NOT NULL,session NVARCHAR(MAX) NOT NULL,iat DATETIME NULL,asl BIGINT DEFAULT -1, CONSTRAINT pk_auth_sessions PRIMARY KEY (sid))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='consent_sessions' and xtype='U') CREATE TABLE consent_sessions (sid VARCHAR(100) NOT NULL,session NVARCHAR(MAX) NOT NULL,iat DATETIME NULL,asl BIGINT DEFAULT -1, CONSTRAINT pk_consent_sessions PRIMARY KEY (sid))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='clients' and xtype='U') CREATE TABLE clients (client_id VARCHAR(80) NOT NULL,client_id_issued_at DATETIME NULL,registration_access_token VARCHAR(200),client_secret VARCHAR(200),client_secret_expires_at DATETIME NULL,grant_types VARCHAR(200),response_types VARCHAR(200),redirect_uris VARCHAR(1000),scope VARCHAR(2000),token_endpoint_auth_method VARCHAR(100),token_endpoint_auth_signing_alg VARCHAR(20),jwks_uri VARCHAR(200),jwks VARCHAR(4000),contacts VARCHAR(200),client_name NVARCHAR(2000),client_uri VARCHAR(1000),logo_uri VARCHAR(1000),policy_uri VARCHAR(1000),tos_uri VARCHAR(1000),software_id VARCHAR(100),software_version VARCHAR(100),application_type VARCHAR(20),subject_type VARCHAR(20),sector_identifier_uri VARCHAR(200),request_uris VARCHAR(1000),request_object_signing_alg VARCHAR(10),request_object_encryption_alg VARCHAR(50),request_object_encryption_enc VARCHAR(50),authorization_signed_response_alg VARCHAR(10),authorization_encrypted_response_alg VARCHAR(50),authorization_encrypted_response_enc VARCHAR(50),require_pushed_authorization_requests BIT NOT NULL,tls_client_auth_subject_dn VARCHAR(200),tls_client_auth_san_dns VARCHAR(100),tls_client_auth_san_uri VARCHAR(100),tls_client_auth_san_ip VARCHAR(45),tls_client_auth_san_email VARCHAR(100),tls_client_certificate_bound_access_tokens BIT NOT NULL,dpop_bound_access_tokens BIT NOT NULL,code_challenge_method VARCHAR(10),id_token_signed_response_alg VARCHAR(10),id_token_encrypted_response_alg VARCHAR(50),id_token_encrypted_response_enc VARCHAR(50),userinfo_signed_response_alg VARCHAR(10),userinfo_encrypted_response_alg VARCHAR(50),userinfo_encrypted_response_enc VARCHAR(50),default_max_age BIGINT DEFAULT -1,require_auth_time BIT NOT NULL,default_acr_values VARCHAR(200),initiate_login_uri VARCHAR(200),frontchannel_logout_uri VARCHAR(200),frontchannel_logout_session_required BIT NOT NULL,backchannel_logout_uri VARCHAR(200),backchannel_logout_session_required BIT NOT NULL,backchannel_token_delivery_mode VARCHAR(4), backchannel_client_notification_endpoint VARCHAR(1000),backchannel_authentication_request_signing_alg VARCHAR(10),backchannel_user_code_parameter BIT NOT NULL,post_logout_redirect_uris VARCHAR(1000),data NVARCHAR(2000),CONSTRAINT pk_clients PRIMARY KEY (client_id))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='federation_clients' and xtype='U') CREATE TABLE federation_clients (entity_id VARCHAR(500) NOT NULL, n INT NOT NULL, anchor_id VARCHAR(500) NOT NULL, reg VARCHAR(20) NOT NULL, cid VARCHAR(100), iat DATETIME NOT NULL, exp DATETIME NOT NULL, misc NVARCHAR(4000), CONSTRAINT pk_federation_clients PRIMARY KEY (entity_id, n))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='client_jwks' and xtype='U') CREATE TABLE client_jwks (client_id VARCHAR(100) NOT NULL,jwks VARCHAR(MAX) NOT NULL,CONSTRAINT pk_client_jwks PRIMARY KEY (client_id))

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='request_jwts' and xtype='U') CREATE TABLE request_jwts (uri VARCHAR(1000) NOT NULL,client_id VARCHAR(80) NOT NULL,clm VARCHAR(MAX) NOT NULL,frg VARCHAR(100),iat DATETIME NULL,rol BIGINT DEFAULT -1, CONSTRAINT pk_request_jwts PRIMARY KEY (uri))

