### ### Additional client metadata checks ### ###

# The default configuration for the additional checks to be performed on OAuth
# 2.0 client / OpenID relying party metadata for a new or updated registration.
# The default configuration can be overridden with Java system properties.
#
# https://connect2id.com/products/server/docs/integration/final-client-metadata-validator

# Enables / disables the additional client metadata checks
op.additionalClientMetadataChecks.enable=true