### ### Key Store Configuration ### ###

# The default key store configuration. Can be overridden with Java system
# properties.
#
# https://connect2id.com/products/server/docs/config/jwk-set

### Encryption key for the key store ###

# 128-bit AES key for encrypting the stored private key material. Required,
# unless the Connect2id server is configured with static JWK sets and / or a
# PKCS#11 (HSM) store. The key must be a JWK of type "oct" (octet sequence
# key), with "use" (key use) "enc" (encryption) and an optional "kid" (key ID).
# The JSON string may be additionally BASE64URL encoded, to prevent character
# escape issues in shell environments.
#
# When specified, this configuration property overrides any encryption key in
# the optional "WEB-INF/keyStoreEncJWK.json" file.
keyStore.encJWK=


### Web API ###

# The access token for the key store web API, represented by its SHA-256 hash
# (in hexadecimal format). The hash is a measure to prevent accidental leakage
# of the token through configuration files, logs, etc. The token is of type
# Bearer, non-expiring and must contain at least 32 random alphanumeric
# characters to make brute force guessing impractical. If not specified the web
# API is disabled.
#
# Additional access tokens, for token roll-over or other needs, can be
# configured by appending a dot (.) with a unique label to the property name,
# e.g. as keyStore.apiAccessTokenSHA256.1=abc...
keyStore.apiAccessTokenSHA256=


### JWK sets ###

# The default size of new generated RSA JWKs. The supported sizes are 2048,
# 3072 and 4096 bits. The default value is 2048.
keyStore.defaultRSAKeySize=2048

# When true and the specified JWK set context ("op" for OpenID provider,
# "federation" for OpenID Federation 1.0) is empty, the key store will
# automatically generate the required JWK set. The default value is true
# (enabled).
keyStore.generateIfEmpty.op=true
keyStore.generateIfEmpty.federation=true

# JWK set to import into the key store if the specified context ("op" for
# OpenID provider, "federation" for OpenID Federation 1.0) is empty. The JSON
# string may be additionally BASE64URL encoded, to prevent character escape
# issues in shell environments. The default value is none.
keyStore.importIfEmpty.op=
keyStore.importIfEmpty.federation=

# Time, as seconds since the Unix epoch, after which any configured JWK sets
# for import will be ignored. Must be not more than 1 day ahead of the current
# time when the Connect2id server starts up.
keyStore.importExp=

# Controls the local caching of JWK sets retrieved from the key store. The
# cache lifetime is specified in seconds. Zero or negative disables caching.
# Must not exceed 600 seconds (10 minutes). The default value is 60 seconds
# (1 minute).
keyStore.jwkSetCacheLifetime=60

# Static JWK set for the specified context ("op" for OpenID provider,
# "federation" for OpenID Federation 1.0). The JSON string may be additionally
# BASE64URL encoded, to prevent character escape issues in shell environments.
# The default value is none.
#
# When a static JWK set is specified for a given context the key store web API
# operations for key rotation and revocation are disabled.
keyStore.staticJWKSet.op=
keyStore.staticJWKSet.federation=

# Enables / disables PKCS#11 (HSM) support for the specified context ("op" for
# OpenID provider, "federation" for OpenID Federation 1.0). The default value
# is false (disabled).
keyStore.pkcs11.op.enable=false
keyStore.pkcs11.federation.enable=false

# The location of the Sun PKCS#11 provider configuration for the specified
# context ("op" for OpenID provider, "federation" for OpenID Federation 1.0).
# The configuration can be alternatively passed inline as a string. The string
# may be additionally BASE64URL encoded, to prevent character escape issues in
# shell environments.
#
# The PKCS#11 provider configuration specifies the driver to load for the HSM
# device, a slot number for it (as multiple HSM devices may be attached), and
# other attributes. These are explained in the Java PKCS#11 Reference Guide at
# https://docs.oracle.com/en/java/javase/17/security/pkcs11-reference-guide1.html
# The manual of your HSM device should also provide information.
keyStore.pkcs11.op.configFile=/WEB-INF/hsm.cfg
keyStore.pkcs11.federation.configFile=

# The password (PIN) required to unlock the HSM for the specified context ("op"
# for OpenID provider, "federation" for OpenID Federation 1.0).
keyStore.pkcs11.op.password=
keyStore.pkcs11.federation.password=

# Optional list of identifiers (aliases) of PKCS#11 keys to load from the HSM
# for the specified context ("op" for OpenID provider, "federation" for OpenID
# Federation 1.0). If omitted or blank all recognised and supported keys will
# be loaded.
keyStore.pkcs11.op.keyIDs.1=
keyStore.pkcs11.op.keyIDs.2=
keyStore.pkcs11.op.keyIDs.3=
keyStore.pkcs11.federation.keyIDs.1=
keyStore.pkcs11.federation.keyIDs.2=
keyStore.pkcs11.federation.keyIDs.3=


### Legacy ###

# Deprecated, use keyStore.staticJWKSet.op instead.
jose.jwkSet=

# Deprecated, use keyStore.staticJWKSet.federation instead.
jose.federation.jwkSet=

# Deprecated, use keyStore.pkcs11.op.enable instead.
pkcs11.enable=

# Deprecated, use keyStore.pkcs11.op.configFile instead.
pkcs11.configFile=

# Deprecated, use keyStore.pkcs11.op.password instead.
pkcs11.password=

# Deprecated, use keyStore.pkcs11.op.keyIDs.* instead.
pkcs11.keyIDs.1=
pkcs11.keyIDs.2=
pkcs11.keyIDs.3=
