### ### Login hint resolver for CIBA configuration ### ###

# The default configuration of the web-based resolver of CIBA login hints to  
# subject identifiers.
#
# https://connect2id.com/products/server/docs/integration/ciba#login-hint-resolver-web

# Enables / disables the login hint resolver. Disabled (false) by default.
op.loginHintResolver.webAPI.enable=false

# The endpoint URL of the web API.
op.loginHintResolver.webAPI.url=

# Access token of type Bearer for the web API.
op.loginHintResolver.webAPI.apiAccessToken=

# The HTTP connect timeout, in milliseconds. The default value is zero, implies
# none or determined by the underlying HTTP client.
op.loginHintResolver.webAPI.connectTimeout=250

# The HTTP response read timeout, in milliseconds. The default value is zero,
# implies none or determined by the underlying HTTP client.
op.loginHintResolver.webAPI.readTimeout=500