### ### Monitoring configuration ### ###

# The default configuration for access to the monitoring endpoint as well as
# metrics reporting via JMX and Graphite. Can be overridden with Java system
# properties.
#
# https://connect2id.com/products/server/docs/config/monitoring


### Web API ###

# The access token for the monitor endpoint, represented by its SHA-256 hash
# (in hexadecimal format). The hash is a measure to prevent accidental leakage
# of the token through configuration files, logs, etc. The token is of type
# Bearer, non-expiring and must contain at least 32 random alphanumeric
# characters to make brute force guessing impractical. If not specified the web
# API is disabled.
#
# Additional access tokens, for token roll-over or for a load balancer to
# monitor the health of the Connect2id server, can be configured by appending a
# dot (.) with a unique label to the property name, e.g. as
# monitor.apiAccessTokenSHA256.1=abc...
#
# Evaluation note: Use token value ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6
monitor.apiAccessTokenSHA256=cca68b8b82bcf0b96cb826199429e50cd95a042f8e8891d1ac56ab135d096633

### General reporting ###

# Timeout for caching entry count results, in seconds. Zero disables caching,
# negative disables readings, causing the gauge to always return -1. The
# default timeout value is 1800 seconds (30 minutes).
#
# Gauges with entry count caching:
#
#   * authzSessionStore.numSessions
#   * sessionStore.numSessions
#   * clientStore.numRegistrations
#   * clientStore.numCachedRemoteJWKSets
#   * clientStore.numCachedRemoteRequestObjects
#   * authzStore.numAuthzCodes
#   * authzStore.numIdAccessTokens
#   * authzStore.numLongLivedAuthorizations
#   * authzStore.numRevocationJournalEntries
#
monitor.entryCountCacheTimeout=1800


### JMX reporting ###

# Enables / disables metrics reporting via JMX.
monitor.enableJMX=false


### Graphite reporting ###

# Enables / disables metrics reporting to a Carbon server.
monitor.graphite.enable=false

# The Carbon server host name / IP address.
monitor.graphite.host=

# The Carbon server port number.
monitor.graphite.port=2003

# The reporting interval, in seconds.
monitor.graphite.reportInterval=60

# Set to a positive integer to enable metrics batching using the Graphite
# pickle protocol. If set to zero batching is disabled, implying use of the
# Graphite plaintext protocol. Note that the pickle and plaintext protocols
# typically require a different port number.
monitor.graphite.batchSize=0

# Optional prefix for the metrics.
monitor.graphite.prefix=

# The time unit for reporting rates. Specified as Java TimeUnit enum constants.
monitor.graphite.ratesTimeUnit=SECONDS

# The time unit for reporting durations. Specified as Java TimeUnit enum
# constants.
monitor.graphite.durationsTimeUnit=MILLISECONDS

# White list of metric names to report to the Carbon server, with wild card
# support. To report all metrics set the filter value to an asterisk `*`. More
# than one filter card may be specified.
monitor.graphite.filter.1=*
monitor.graphite.filter.2=
monitor.graphite.filter.3=