### ### Subject (end-user) session store configuration ### ###

# The default configuration of the store for end-user sessions. Can be
# overridden with Java system properties.
#
# https://connect2id.com/products/server/docs/config/session-store


### Web API ###

# The access token for the subject session store web API, represented by its
# SHA-256 hash (in hexadecimal format). The hash is a measure to prevent
# accidental leakage of the token through configuration files, logs,
# etc. The token is of type Bearer, non-expiring and must contain at least 32
# random alphanumeric characters to make brute force guessing impractical. If
# not specified the web API is disabled.
#
# Additional access tokens, for token roll-over or other needs, can be
# configured by appending a dot (.) with a unique label to the property name,
# e.g. as sessionStore.apiAccessTokenSHA256.1=abc...
#
# Evaluation note: Use token value ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6
sessionStore.apiAccessTokenSHA256=cca68b8b82bcf0b96cb826199429e50cd95a042f8e8891d1ac56ab135d096633


### Session defaults and policies ###

# The default maximum session lifetime, in minutes. Applied to newly created
# subject sessions with an omitted max_life value. A negative value implies no
# time limit. Must not be zero. The default value is 259200 minutes (180 days).
sessionStore.maxLifetime=259200

# The default maximum authentication lifetime, in minutes. Applied to newly
# created subject sessions with an omitted auth_life value. A negative value
# implies no time limit. Must not be zero. The default value is 10080 minutes
# (30 days).
sessionStore.authLifetime=43200

# The default maximum session idle time, in minutes. Applied to newly created
# subject sessions with an omitted max_idle value. A negative value implies no
# time limit. Must not be zero. The default value is 1440 minutes (10 days).
sessionStore.maxIdleTime=14400

# The maximum number of concurrent sessions a subject may have. Must not exceed
# 25 concurrent sessions. The default value is 5.
sessionStore.quotaPerSubject=5

# The maximum number of concurrent native IdP app sessions a subject may have.
# Must not exceed 5 concurrent sessions. Zero disables native IdP app sessions.
# The default value is 1.
sessionStore.nativeIdPAppQuotaPerSubject=1

# The login behaviour when a subject exhausts their session quota. The default
# value is CLOSE_OLD_SESSION.
#
# Policy values:
#
#     * DENY_LOGIN -- The login request must be rejected.
#     * CLOSE_OLD_SESSION -- The next expiring session for the subject must be
#       closed and the new login request must be allowed to proceed. This is
#       the default policy.
#
sessionStore.onQuotaExhaustion=CLOSE_OLD_SESSION

# Set to "true" to accept legacy session identifiers (SID) without HMAC
# protection. Required to enable import of sessions from Connect2id server
# versions 5.x and older. The default value is false.
sessionStore.acceptLegacySIDs=false


### Internal configuration ###

# The interval for purging orphaned subject index keys, in seconds. If less
# than 1 the purge thread is disabled. The default value is -1 (disabled).
sessionStore.internal.subjectIndexPurgeInterval=-1