### ### Software statement verifier configuration ### ###

# The default configuration of the verifier of optional software statements
# included in client registration requests. Can be overridden with Java system
# properties.
#
# See:
#
# 1. https://connect2id.com/products/server/docs/integration/registration-interceptor
# 2. https://bitbucket.org/connect2id/software-statement-verifier
# 3. https://bitbucket.org/connect2id/server-sdk

### Basic configuration ###

# Enables / disables the HTTP claims source. Disabled by default.
op.ssv.enable=false

# The accepted "iss" (issuer) claim of the software statements.
op.ssv.issuer=

# The URL of the public JWK set for verifying the software statement
# signatures.
op.ssv.issuerJWKSetURL=

# The accepted JWS algorithms for the software statements, as comma and / or
# space separated list.
op.ssv.jwsAlgorithms=RS256

# The accepted "typ" (type) JWT header values of the software statements, as
# comma and / or space separated list. If blank or omitted the JWT type
# checking will accept software statements with no "typ" header or the header
# value "JWT".
op.ssv.jwtTypes=

# The timeout in milliseconds for establishing HTTP connections, such as those
# to retrieve the JWK set. If zero the underlying HTTP client library will
# determine the timeout.
op.ssv.connectTimeout=1000

# The timeout in milliseconds for obtaining HTTP responses after connection. If
# zero the underlying HTTP client library will determine the timeout.
op.ssv.readTimeout=1000

# Access token of type bearer (non-expiring) for accessing the client
# registration endpoint. Client registration HTTP POST requests with a merged
# valid software statement will have their "Authorization" header set to this
# token, thus authorising the request at the underlying registration endpoint.
# See the Connect2id server op.reg.apiAccessTokenSHA256 configuration property.
op.ssv.registrationAccessToken=ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6

# The names of additional claims that must be present in the software statement
# other than the "iss" (issuer) claim, as comma and / or space separated list.
# If blank or omitted the only required claim is the standard "iss" (issuer)
# claim.
op.ssv.additionalRequiredClaims=

# Names of software statement claims to log at INFO level under "SSV0100", as
# comma and / or space separated list. If blank or omitted only the standard
# "iss" (issuer) claim will be logged.
op.ssv.logClaims=


### Optional client X.509 certificate configuration ###

# If true the HTTP POST request must include a client X.509 certificate
# validated by the TLS terminator / reverse proxy. The default value if blank
# or omitted is false.
op.ssv.clientX509Certificate.require=false

# The required root DN (distinguished name) of the client X.509 certificates,
# if client certificates are required. If blank or omitted the certificate root
# DN is not checked.
op.ssv.clientX509Certificate.rootDN=


### Optional request JWT configuration ###

# The accepted HTTP POST request type. The default value if blank or omitted is
# "JSON".
#
#     * JSON -- The request entity content type must be "application/json".
#      This is the standard type, according to the OAuth 2.0 Dynamic Client
#      Registration Protocol (RFC7591).
#     * JWT -- The request entity content type must be "application/jwt" and
#      the JWT must be signed with an accepted JWS algorithm.
#
op.ssv.requestType=JSON

# The URI of the public JWK set for verifying request JWT signatures (not the
# software statements!). Supported URI types:
#
#     * "https" or "http" URL of the JWK set.
#     * URN with in the form of "urn:software_statement:[url-claim-name]" where
#       "[urn-claim-name]" is the name of a software statement claim with a
#       "https" or "http" URL of the JWK set to use. If a registration request
#       JWT is to be validated successfully in this way it must include a valid
#       signed software statement.
#
op.ssv.requestJWT.jwkSetSource=

# The accepted JWS algorithms for the registration request JWT, as comma and /
# or space separated list.
op.ssv.requestJWT.jwsAlgorithms=

# The names of claims that must be present in a registration request JWT, as
# comma and / or space separated list, if blank or omitted none. If the "aud"
# (audience) claim is included it will be matched against the Connect2id server
# issuer URL. If the "exp" (expiration) claim is included it will be checked
# accordingly.
op.ssv.requestJWT.requiredClaims=


### Optional client metadata transformations ###

# Names of top-level JSON object members to be removed from the client
# metadata, as comma and / or space separated list. If blank or omitted no
# members will be removed. Can be used to scrub software statement and request
# JWT claims which are intended for the JWT verification only and should not be
# passed on with the client registration request.
op.ssv.transforms.remove=

# Map of names of top-level JSON object members to be renamed in the client
# metadata. For example, the following configuration property will cause
# "software_jwks_endpoint" to be renamed as "jwks_uri" and thus be picked as a
# standard OAuth client registration parameter.
# op.ssv.transforms.rename.software_jwks_endpoint=jwks_uri
op.ssv.transforms.rename.*=

# Names of top-level JSON object members in the client metadata to be moved
# into the "data" JSON object member, as comma and / or space separated list.
# If blank or omitted no members will be moved. The Connect2id server uses the
# custom "data" client metadata parameter (of type JSON object) to enable
# storing of additional non-standard parameters for the client. Top-level
# parameters which are not recognised will be scrubbed from the client
# registration.
op.ssv.transforms.moveIntoData=