### LdapAuth service configuration ###


# Access control #

ldapAuth.access.https.require = false
ldapAuth.access.https.requireClientCert = false
ldapAuth.access.https.clientCertPrincipal = cn=myapp,ou=apps,dc=example,dc=com

ldapAuth.access.hosts.allow = *

ldapAuth.access.apiKeys.require = false
ldapAuth.access.apiKeys.exemptedMethods = ws.getName ws.getVersion ws.getTime
ldapAuth.access.apiKeys.map.f70defbeb88141f88138bea52b6e1b9c = user.auth realm.get
ldapAuth.access.apiKeys.map.08d1e641b1c14d888796e47c06430efb = *


# Web API settings #

ldapAuth.api.allowUserAuthRequests = true
ldapAuth.api.allowUserAuthGetRequests = true
ldapAuth.api.allowUserGetRequests = false
ldapAuth.api.allowUserResolveDNRequests = true

ldapAuth.api.enableDNProvision = true
ldapAuth.api.allowJson2LdapCIDProvision = false

ldapAuth.api.exposeExceptions = false
ldapAuth.api.reportRequestProcTime = false
ldapAuth.api.responseContentType = application/json;charset=utf-8


# Authenticating backend #

ldapAuth.authRealm = wonderland.net
ldapAuth.authBackend = LDAP


# Json2Ldap gateway / proxy #

ldapAuth.json2ldap.url = http://localhost:8080/json2ldap/
ldapAuth.json2ldap.useDefaultLDAPServer = true
ldapAuth.json2ldap.trustSelfSignedCerts = false
ldapAuth.json2ldap.connectTimeout = 500
ldapAuth.json2ldap.readTimeout = 1000


# LDAP server #

ldapAuth.ldapServer.url = ldap://localhost:11389 ldap://remotehost:11389
ldapAuth.ldapServer.selectionAlgorithm = FAILOVER
ldapAuth.ldapServer.connectTimeout = 500
ldapAuth.ldapServer.security = NONE
ldapAuth.ldapServer.trustSelfSignedCerts = false
ldapAuth.ldapServer.connectionPoolSize = 10
ldapAuth.ldapServer.connectionPoolMaxWaitTime = 500
ldapAuth.ldapServer.connectionMaxAge = 0


# User DN resolution #

ldapAuth.dnResolution.method = SEARCH
ldapAuth.dnResolution.dnTemplate = uid=%u,ou=people,dc=wonderland,dc=net
ldapAuth.dnResolution.searchUserDN =
ldapAuth.dnResolution.searchUserPassword =
ldapAuth.dnResolution.searchBaseDN = ou=people,dc=wonderland,dc=net
ldapAuth.dnResolution.searchScope = ONE
ldapAuth.dnResolution.searchFilter = (|(uid=%u)(mail=%u))


# User attributes for retrieval #

ldapAuth.userAttributes.single.userID = uid
ldapAuth.userAttributes.single.name = cn
ldapAuth.userAttributes.multi.email = mail
ldapAuth.userAttributes.multi.phone = telephoneNumber mobile homePhone


# Custom trust and key store #

ldapAuth.customTrustStore.enable = false
ldapAuth.customTrustStore.file =
ldapAuth.customTrustStore.password =
ldapAuth.customTrustStore.type =

ldapAuth.customKeyStore.enable = false
ldapAuth.customKeyStore.file =
ldapAuth.customKeyStore.password =
ldapAuth.customKeyStore.type =
