/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.39
 * Generated at: 2025-04-21 15:57:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.nimbusds.tenants.manager.*;
import com.nimbusds.oauth2.sdk.as.*;
import com.nimbusds.openid.connect.sdk.op.*;
import com.nimbusds.openid.connect.provider.*;
import com.nimbusds.openid.connect.provider.config.*;
import com.nimbusds.openid.connect.provider.splash.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(12);
    _jspx_imports_packages.add("com.nimbusds.openid.connect.provider.splash");
    _jspx_imports_packages.add("com.nimbusds.oauth2.sdk.as");
    _jspx_imports_packages.add("com.nimbusds.openid.connect.provider");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("com.nimbusds.openid.connect.provider.config");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.nimbusds.openid.connect.sdk.op");
    _jspx_imports_packages.add("com.nimbusds.tenants.manager");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;



    OIDCProviderMetadata opMetadata = null;
    boolean invalidTenantError = false;
    try {
        TenantContext tenantCtx = ProviderContext.from(application)
                .getTenantResolver()
                .resolveTenantContext(request.getHeader("Issuer"), request.getHeader("Tenant-ID"));

        SplashPage splashPage = new Configuration(tenantCtx.getTenantProperties()).splashPage;

        if (SplashPage.DEFAULT.equals(splashPage)) {
            // continue with default page
            opMetadata = ProviderContext.from(application).getProviderMetadataFactory().compose(tenantCtx);
        } else if (SplashPage.BLANK.equals(splashPage)) {
            response.setStatus(200);
            return;
        } else if (SplashPage.OP_METADATA.equals(splashPage)) {
            response.setStatus(301);
            response.setHeader("Location", tenantCtx.getIssuer() + OIDCProviderConfigurationRequest.OPENID_PROVIDER_WELL_KNOWN_PATH);
            return;
        } else {
            response.setStatus(301);
            response.setHeader("Location", splashPage.getURI().toString());
            return;
        }

    } catch (TenantUnavailableException e) {
        response.setStatus(400); // Bad Request
        invalidTenantError = true;
    }

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("	<head>\n");
      out.write("		<title>Connect2id Server</title>\n");
      out.write("        ");
 response.setHeader("Content-Security-Policy", "default-src 'self'"); 
      out.write("\n");
      out.write("		<meta charset=\"utf-8\">\n");
      out.write("        <meta content=\"no-cache\" http-equiv=\"cache-control\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/font-ptsans.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/normalize.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"css/main.css\">\n");
      out.write("	</head>\n");
      out.write("	<body>\n");
      out.write("\n");
      out.write("		<h1>Connect2id Server ");
      out.print( ProviderSpec.SOFTWARE_VERSION );
      out.write("</h1>\n");
      out.write("\n");
      out.write("		");


        if (invalidTenantError) {

            
      out.write("<h2>Error: Invalid tenant or tenant disabled</h2>");


	    } else {

            
      out.write("<h2>Standard OAuth 2.0 / OpenID Connect 1.0 endpoints:</h2>\n");
      out.write("\n");
      out.write("            <table>\n");
      out.write("                <colgroup>\n");
      out.write("                    <col class=\"col-1\"/>\n");
      out.write("                    <col class=\"col-2\"/>\n");
      out.write("                    <col class=\"col-3\"/>\n");
      out.write("                </colgroup>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Server metadata</td>\n");
      out.write("                    ");

                        String opMetadataURLString = opMetadata.getIssuer() + OIDCProviderConfigurationRequest.OPENID_PROVIDER_WELL_KNOWN_PATH;
                        String asMetadataURLString = opMetadata.getIssuer() + AuthorizationServerConfigurationRequest.OAUTH_SERVER_WELL_KNOWN_PATH;
                    
      out.write("\n");
      out.write("                    <td><a href=\"");
      out.print( opMetadataURLString );
      out.write('"');
      out.write('>');
      out.print( opMetadataURLString );
      out.write("</a><br/>\n");
      out.write("                        <a href=\"");
      out.print( asMetadataURLString );
      out.write('"');
      out.write('>');
      out.print( asMetadataURLString );
      out.write("</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/discovery\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Federation metadata</td>\n");
      out.write("                    ");
 if (opMetadata.getClientRegistrationTypes() != null) {
                        
      out.write("<td><a href=\"");
      out.print( opMetadata.getIssuer() );
      out.write("/.well-known/openid-federation\">");
      out.print( opMetadata.getIssuer() );
      out.write("/.well-known/openid-federation</a></td>");

                    } else {
                        
      out.write("<td>disabled</td>");

                    } 
      out.write("\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/federation-entity-configuration\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>JWK set</td>\n");
      out.write("                    <td><a href=\"");
      out.print( opMetadata.getJWKSetURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getJWKSetURI() );
      out.write("</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/jwk-set\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Signed JWK set</td>\n");
      out.write("                    ");
 if (opMetadata.getSignedJWKSetURI() != null) {
			            
      out.write("<td><a href=\"");
      out.print( opMetadata.getSignedJWKSetURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getSignedJWKSetURI() );
      out.write("</a></td>");

                    } else {
                        
      out.write("<td>disabled</td>");

                    } 
      out.write("\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/jwk-set\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Client registration</td>\n");
      out.write("                    <td><a href=\"");
      out.print( opMetadata.getRegistrationEndpointURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getRegistrationEndpointURI() );
      out.write("</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/client-registration\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Federation client registration</td>\n");
      out.write("                    ");
 if (opMetadata.getFederationRegistrationEndpointURI() != null) {
                        
      out.write("<td><a href=\"");
      out.print( opMetadata.getFederationRegistrationEndpointURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getFederationRegistrationEndpointURI() );
      out.write("</a></td>");

                    } else {
                        
      out.write("<td>disabled</td>");

                    } 
      out.write("\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/federation-client-registration\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>PAR</td>\n");
      out.write("                    <td><a href=\"");
      out.print( opMetadata.getPushedAuthorizationRequestEndpointURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getPushedAuthorizationRequestEndpointURI() );
      out.write("</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/par\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Authorization</td>\n");
      out.write("                    <td><a href=\"");
      out.print( opMetadata.getAuthorizationEndpointURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getAuthorizationEndpointURI() );
      out.write("</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/authorization\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>CIBA</td>\n");
      out.write("                    <td><a href=\"");
      out.print( opMetadata.getBackChannelAuthenticationEndpointURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getBackChannelAuthenticationEndpointURI() );
      out.write("</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/ciba\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Token</td>\n");
      out.write("                    <td><a href=\"");
      out.print( opMetadata.getTokenEndpointURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getTokenEndpointURI() );
      out.write("</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/token\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Token introspection</td>\n");
      out.write("                    <td><a href=\"");
      out.print( opMetadata.getIntrospectionEndpointURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getIntrospectionEndpointURI() );
      out.write("</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/token-introspection\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Token revocation</td>\n");
      out.write("                    <td><a href=\"");
      out.print( opMetadata.getRevocationEndpointURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getRevocationEndpointURI() );
      out.write("</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/token-revocation\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>UserInfo</td>\n");
      out.write("                    <td><a href=\"");
      out.print( opMetadata.getUserInfoEndpointURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getUserInfoEndpointURI() );
      out.write("</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/userinfo\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Check session</td>\n");
      out.write("                    ");
 if (opMetadata.getCheckSessionIframeURI() != null) {
                        
      out.write("<td><a href=\"");
      out.print( opMetadata.getCheckSessionIframeURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getCheckSessionIframeURI() );
      out.write("</a></td>");

                    } else {
                        
      out.write("<td>disabled</td>");

                    } 
      out.write("\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/check-session\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>End session</td>\n");
      out.write("                    ");
 if (opMetadata.getEndSessionEndpointURI() != null) {
                        
      out.write("<td><a href=\"");
      out.print( opMetadata.getEndSessionEndpointURI() );
      out.write('"');
      out.write('>');
      out.print( opMetadata.getEndSessionEndpointURI() );
      out.write("</a></td>");

                    } else {
                        
      out.write("<td>disabled</td>");

                    } 
      out.write("\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/api/logout\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("            <h2>Integration endpoints:</h2>\n");
      out.write("\n");
      out.write("            ");
 String baseURL = opMetadata.getIssuer() + "/"; 
      out.write("\n");
      out.write("\n");
      out.write("            <table>\n");
      out.write("                <colgroup>\n");
      out.write("                    <col class=\"col-1\"/>\n");
      out.write("                    <col class=\"col-2\"/>\n");
      out.write("                    <col class=\"col-3\"/>\n");
      out.write("                </colgroup>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Authorization session</td>\n");
      out.write("                    <td><a href=\"");
      out.print( baseURL );
      out.write("authz-sessions/rest/v3\">");
      out.print( baseURL );
      out.write("authz-sessions/rest/v3</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/integration/authz-session\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Logout session</td>\n");
      out.write("                    <td><a href=\"");
      out.print( baseURL );
      out.write("logout-sessions/rest/v1\">");
      out.print( baseURL );
      out.write("logout-sessions/rest/v1</a><br/>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/integration/logout-session\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>CIBA sessions</td>\n");
      out.write("                    <td><a href=\"");
      out.print( baseURL );
      out.write("ciba-sessions/rest/v1\">");
      out.print( baseURL );
      out.write("ciba-sessions/rest/v1</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/integration/ciba\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Direct authorization</td>\n");
      out.write("                    <td><a href=\"");
      out.print( baseURL );
      out.write("direct-authz/rest/v2\">");
      out.print( baseURL );
      out.write("direct-authz/rest/v2</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/integration/direct-authz\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Subject session store</td>\n");
      out.write("                    <td><a href=\"");
      out.print( baseURL );
      out.write("session-store/rest/v2\">");
      out.print( baseURL );
      out.write("session-store/rest/v2</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/integration/session-store\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Authorization store</td>\n");
      out.write("                    <td><a href=\"");
      out.print( baseURL );
      out.write("authz-store/rest/v3\">");
      out.print( baseURL );
      out.write("authz-store/rest/v3</a><br/>\n");
      out.write("                        <a href=\"");
      out.print( baseURL );
      out.write("authz-store/rest/v2\">");
      out.print( baseURL );
      out.write("authz-store/rest/v2</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/integration/authz-store\">docs</a><br/>\n");
      out.write("                        <a href=\"https://connect2id.com/products/server/docs/archive/v9/integration/authz-store\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Key store</td>\n");
      out.write("                    <td><a href=\"");
      out.print( baseURL );
      out.write("key-store/rest/v1\">");
      out.print( baseURL );
      out.write("key-store/rest/v1</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/integration/key-store\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Security Token Service (STS)</td>\n");
      out.write("                    <td><a href=\"");
      out.print( baseURL );
      out.write("sts/rest/v1\">");
      out.print( baseURL );
      out.write("sts/rest/v1</a><br/>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/integration/sts\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Monitoring</td>\n");
      out.write("                    <td><a href=\"");
      out.print( baseURL );
      out.write("monitor/v1\">");
      out.print( baseURL );
      out.write("monitor/v1</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/integration/monitoring\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Configuration check</td>\n");
      out.write("                    <td><a href=\"");
      out.print( baseURL );
      out.write("config/check\">");
      out.print( baseURL );
      out.write("config</a></td>\n");
      out.write("                    <td><a href=\"https://connect2id.com/products/server/docs/integration/config\">docs</a></td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("            <h2>Notes:</h2>\n");
      out.write("\n");
      out.write("            <table style=\"width: 45em\">\n");
      out.write("                <tr>\n");
      out.write("                    <td>Use the dedicated <a href=\"https://connect2id.com/products/server/docs/integration/monitoring#healthcheck\">resource</a>\n");
      out.write("                        for Connect2id server health checks, not this URL.</td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("        ");

	    } // if (invalidTenantError)
	    
      out.write("\n");
      out.write("\n");
      out.write("		<hr/>\n");
      out.write("\n");
      out.write("		<p><a href=\"https://connect2id.com\"><img id=\"logo\" src=\"css/connect2id-logo.png\" alt=\"Connect2id\"/></a>\n");
      out.write("		  &copy; 2012 - 2025, <a href=\"https://connect2id.com\">Connect2id Ltd.</a></p>\n");
      out.write("\n");
      out.write("	</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
