### Logout Page Configuration ###

# Note: Java system properties can be used to override the configuration
# properties below, e.g. at JVM startup with -DlogoutPage.cookieName=sid

# The Connect2id server logout session API endpoint. See
# https://connect2id.com/products/server/docs/integration/logout-session
logoutPage.apiEndpoint=http://127.0.0.1:8080/c2id/logout-sessions/rest/v1

# The bearer access token for the logout session API. See
# https://connect2id.com/products/server/docs/config/core#op-logout-apiAccessToken
logoutPage.apiAccessToken=ztucZS1ZyFKgh0tUEruUtiSTXhnexmd6

# The name of the HTTP cookie used to store the subject (end-user) session ID.
logoutPage.cookieName=sid

# Optional default post logout redirection URL. If set the logout page will
# redirect to it if the OpenID client that requested logout doesn't provide
# one.
logoutPage.defaultPostLogoutRedirectURI=