server.port=8181
issuer=http://localhost:8081
trustAnchors=http://trustanchor1.example.org,http://trustanchor2.example.org,http://trustanchor3.example.org
authorityHints=http://authorityhints1.example.org,http://authorityhints2.example.org,http://authorityhints3.example.org