# By default OFS port is set to 8181
server.port=8181

#Issuer ID including port
issuer=http://localhost:8181

# MUST have at least one Trust Anchor. Use comma for multiple Trust Anchors.
trustAnchors=http://trustanchor1.example.org

# Trust Anchors with no Superiors MUST NOT have authority hints.
authorityHints=http://authorityhints1.example.org,http://authorityhints2.example.org,http://authorityhints3.example.org