### OpenID Connect client properties ###

# The default OpenID Connect Provider (OP) properties #
op.iss=http://127.0.0.1:8080/c2id
op.jwks_uri=http://127.0.0.1:8080/c2id/jwks.json
op.authz_uri=http://127.0.0.1:8080/c2id-login
op.token_uri=http://127.0.0.1:8080/c2id/token
op.userinfo_uri=http://127.0.0.1:8080/c2id/userinfo
op.scopes=openid,email,profile,phone,address,offline_access

# The default OpenID Connect Client (RP) properties #
rp.client_id=000123
rp.client_secret=7wKJNYFaKKg4FxUdi8_R75GGYsiWezvAbcdN1uSumE4
rp.redirect_uri=http://127.0.0.1:8080/oidc-client/cb
rp.token_endpoint_auth_method=client_secret_basic
rp.token_endpoint_auth_signing_alg=