{{ if .Values.postgresql.enabled }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-setup"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: 0.0.1
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      annotations:
        "proxy.istio.io/config": '{ "holdApplicationUntilProxyStarts": true }'
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "{{ .Values.takserver.takserverDatabaseSetup.image.repository }}:{{ .Values.takserver.takserverDatabaseSetup.image.tag }}"
        env:
          - name: 'region'
            value: 'aws-rds-placeholder'
          - name: 'identifier'
            value: 'aws-rds-placeholder'
          - name: POSTGRES_DB
            value: {{ .Values.global.postgresql.auth.database }}
          - name: POSTGRES_USER
            value: {{ .Values.global.postgresql.auth.username }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.global.postgresql.auth.password }}
          - name: POSTGRES_HOST
            value: "{{ .Values.global.postgresql.host }}"
          - name: POSTGRES_PORT
            value: "{{ .Values.global.postgresql.port }}"
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
{{- end }}
